products = [{
    "id": 12345235,
    "name": "Футболка UZcotton мужская",
    "photo": "img/products/T-shirt.svg",
    "color": "белый",
    "size": "56",
    "location": "Коледино WB",
    "seller": "ООО Вайлдберриз",
    "amount": 2,
    "price": 1051,
    "discount": 55,
    "distance": 2,
    "OGRN": "5167746237148",
    "address": "129337, Москва, улица Красная Сосна, 2, корпус 1, стр. 1, помещение 2, офис 34"
}, {
    "id": 34590348760,
    "name": "Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe",
    "photo": "img/products/Case.svg",
    "color": "прозрачный",
    "size": "",
    "location": "Коледино WB",
    "seller": "ООО Мегапрофстиль",
    "amount": 200,
    "price": 11500,
    "distance": 2,
    "discount": 30,
    "OGRN": "5167746237148",
    "address": "129337, Москва, улица Красная Сосна, 2, корпус 1, стр. 1, помещение 2, офис 34"
}, {
    "id": 67443278283,
    "name": "Карандаши цветные Faber-Castell \"Замок\", набор 24 цвета, заточенные, шестигранные, Faber-Castell",
    "photo": "img/products/Pencils.svg",
    "color": "",
    "size": "",
    "location": "Коледино WB",
    "seller": "ООО Вайлдберриз",
    "amount": 0,
    "price": 475,
    "discount": 40,
    "distance": 3,
    "OGRN": "5167746237148",
    "address": "129337, Москва, улица Красная Сосна, 2, корпус 1, стр. 1, помещение 2, офис 34"
}]